---
# Source: kubewatch/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-1.1.1
    heritage: Helm
    release: kubewatch
  name: kubewatch
