# This values.yaml file contains the values needed to enable HA mode.
# Usage:
#   helm install \
#  --set-file global.identityTrustAnchorsPEM=ca.crt \
#  --set-file identity.issuer.tls.crtPEM=issuer.crt \
#  --set-file identity.issuer.tls.keyPEM=issuer.key \
#  --set identity.issuer.crtExpiry=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ") \
#  linkerd/linkerd2

enablePodAntiAffinity: true

global:
  # identity trust
  identityTrustAnchorsPEM: ca.crt
  # proxy configuration
  proxy:
    resources:
      cpu:
        limit: "1"
        request: 100m
      memory:
        limit: 250Mi
        request: 20Mi

# controller configuration
controllerReplicas: 3
controllerResources: &controller_resources
  cpu: &controller_resources_cpu
    limit: "1"
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi
destinationResources: *controller_resources
publicAPIResources: *controller_resources

# identity configuration
identityResources:
  cpu: *controller_resources_cpu
  memory:
    limit: 250Mi
    request: 10Mi

# grafana configuration
grafana:
  resources:
    cpu: *controller_resources_cpu
    memory:
      limit: 1024Mi
      request: 50Mi

# heartbeat configuration
heartbeatResources: *controller_resources

# prometheus configuration
prometheus:
  resources:
    cpu:
      limit: "4"
      request: 300m
    memory:
      limit: 8192Mi
      request: 300Mi

# proxy injector configuration
proxyInjectorResources: *controller_resources
webhookFailurePolicy: Fail

# service profile validator configuration
spValidatorResources: *controller_resources

# tap configuration
tapResources: *controller_resources

# web configuration
webResources: *controller_resources
