apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

nameSuffix: -staging

secretGenerator:
  - name: kubewatch-config
    namespace: kube-system
    behavior: replace
    files:
      - .kubewatch.yaml