---
# Source: linkerd2/templates/namespace.yaml
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
  labels:
    linkerd.io/is-control-plane: "true"
    config.linkerd.io/admission-webhooks: disabled
    linkerd.io/control-plane-ns: linkerd
---
# Source: linkerd2/templates/namespace.yaml
###
### Linkerd Namespace
###
