---
# Source: linkerd2/templates/sp-validator-rbac.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: linkerd
---
# Source: linkerd2/templates/sp-validator-rbac.yaml
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-sp-validator-tls
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/helm stable-2.8.1
type: Opaque
data:
  crt.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lSQUlMcit5dG5RdUR3MzFNQnZMSHBSODh3RFFZSktvWklodmNOQVFFTEJRQXcKS3pFcE1DY0dBMVVFQXhNZ2JHbHVhMlZ5WkMxemNDMTJZV3hwWkdGMGIzSXViR2x1YTJWeVpDNXpkbU13SGhjTgpNakF3TnpJNU1UY3lNakF3V2hjTk1qRXdOekk1TVRjeU1qQXdXakFyTVNrd0p3WURWUVFERXlCc2FXNXJaWEprCkxYTndMWFpoYkdsa1lYUnZjaTVzYVc1clpYSmtMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU0zTVRnbmcxdVloQkh2R1FJVnpYNkdsOWt0MGhETXBHTkQyY0k3S0s1YzNnaDVHVDlzaApLQWJRTGd4bTc5d1VzbzJIWTRQNWIxcURROHo4dHF1V2VkK0xKWEVoeFd5Rk43MUdZVWRsVkhNdWRBNE0yRFNICnRUTkVlWDNDZEJQYlpZMnl2blhlT1hJL0VBK2d5b0IyWVVXaHRmS3ZZTzgways4ZDQ2TnR1RTh0ZDVjUm1zQnQKNDhURElneGl5Y3JPYnVVSndCbTRCTXlrN1N0NFhKRTZZTGRiT0c3aENZOXZBTTg5a3FOZmpZdGhmNXhiRFZMLwphNm00ZTRoOUNRTG0wT3VSMWdYc0gxZU42YVZkNG9OUmxaRW50Q3MyWWVWWitDQ1kzYUl3U3BadnJQUkRJNzBQCjUxSDN5VU1oRElKZnNCUkRNLzFSOHVNbytVYW50REMvblprQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUUQKQWdLa01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDc0VyOXYxeUhCblBuWGp2WXBZOW1tM2JORUFSMlZiRXdJClZ5dUZrRmlCemdnNm1vaE54TEphY0JCVCtYT09IQzBlOHltdzRndzRpckR6Z3lVbzZmZERXQ0RpaktsVllwNTAKQkl3c1N1bVZZSFZhcUNzcENJNnZYdzY3RVFzL2hMVHNOVWVqanc0Z0dKSy9CSGtJYk85WWdibFRQd1lyU2V6WApSU0hTKzJ6RUpTOUZMSVJ2akhDWXdrV2RWWk9BLzU4eDI2UmlJRXZpS0ZuTHd0YVJaR09HK0hoNUlpQTZ5OWRkCmozMjVZRnZ1dFMzN3RwakxpMXQwd0VNWUtIeHZ5MU5MWkpJbHRFYlY1dEcvajFrY0U4QU1KVk5DUjRjMHRTVjkKK3lueE5sR1BPK2ZNU0luczNpNlI5cTN6R2xzb1lDb0s2N3JWWFE0blFWdDF6QXZvS0ZDcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBemN4T0NlRFc1aUVFZThaQWhYTmZvYVgyUzNTRU15a1kwUFp3anNvcmx6ZUNIa1pQCjJ5RW9CdEF1REdidjNCU3lqWWRqZy9sdldvTkR6UHkycTVaNTM0c2xjU0hGYklVM3ZVWmhSMlZVY3k1MERnelkKTkllMU0wUjVmY0owRTl0bGpiSytkZDQ1Y2o4UUQ2REtnSFpoUmFHMThxOWc3elNUN3gzam8yMjRUeTEzbHhHYQp3RzNqeE1NaURHTEp5czV1NVFuQUdiZ0V6S1R0SzNoY2tUcGd0MXM0YnVFSmoyOEF6ejJTbzErTmkyRi9uRnNOClV2OXJxYmg3aUgwSkF1YlE2NUhXQmV3ZlY0M3BwVjNpZzFHVmtTZTBLelpoNVZuNElKamRvakJLbG0rczlFTWoKdlEvblVmZkpReUVNZ2wrd0ZFTXovVkh5NHlqNVJxZTBNTCtkbVFJREFRQUJBb0lCQUgzUWczMGlpZjdTL0t5MgovVWNZeThSRmRCZVpPaUVVNU9rTFlMRExCRzlFTGpaWUFnWVRkU2NGS3NIR1JLbWx0YXMwdERCQTFFVGZyeG1vCi9meFUyRmxEOWpYOTBYYVEwd3pSOURMenpmZEUxUXFwNjV2aHczTitUMUFGQzNZQVVVdVpsVHIyQ3VTL2pSQWcKMnV4Q2N5Rmd4WjJDZnA1KzVGbnhTZlBsNWlId3JjSGkyZ3BGa2VVM2FJYng5ZmZNMm1wZFBGajFGdTFzdUlSVQo3Z0hxN0d4L2Q5Z3p0eUxXZ2d5cmRwWHR1UFp2LzlYbUtzQm03WnlCbkgxc09TWDhzZXdDb1ROT1BWcDk4bVhwCnMwNjlnODcvamcrb1lyUWMyVXpxc0w1L3U5enBwUUx6VGhGck83VzMyS21yZlJzd0FnWmdMSEtoUFkxVCtXYkcKM3B1eXhDRUNnWUVBempCbU5yZDM2MWJTTHNlcmlXcUhPcVhrZGxjcHFWYjdhbDFITml3RGJvVXJFRWRKd0lCTgozSFF5NndrVmZUOVpYV3EwVDE3NDVaNDlsL1k5MFZQWjFtZHkvTkN2WHpJWXFSY2V5dEt3ZHpqTFFEYTlNUnNjCmNZY3FqY2hjZmMrNzc1dEZ4MXprT0NqUE1nSlB6NjJSNU5YZUZZeVdxRlJ0MWwwY0R0bURPWVVDZ1lFQS80TzUKa0NRQTVUUjNVbnRhK0JaWXpKMWFvck16RFhxNWo4ZzNDZlQxYlNpUTk3ekpvREhxZXgzdm0wTWNEY3FUUVlEQQp0NlpMRzZOd1oyUlhMS0R4bTFKS3Y4UDdPcGJXUnR0Rzhac2hSbGNDdWJVVENKd2pDZkZKTjRablRmckt4ODlMCmZCQVFhQ1Jyb0dmdXdJQTUxUGROKzlzQXlDVWtVS0ZrM2FRYTVnVUNnWUExc2Y3OFl0MFU2WUJFOUhTa2paeDMKMW5uZm82VlMxemNVSlFTRmhBTEV4bU5Ia3ZrTzY1cmJQVnVCUDlWYno2S0xKRjJlaWVJUmtoc0NOdnMwUnp6awppLzR5L25tZE5lT2NMVXcwajVlckJKeFJ0YStoV1NrWUc1WW1aRFpLQVU0MUFOKzBJbW5BZ2tnckF0VWNCVnlJCkZuWUdjSjFQYXVWTHZPV3dyRTV6TFFLQmdIald3U0ZzQlloZ1liWCtaSzFEVkVlZ2UwYkszUEFaQkR6OWdSb1MKWVNkNHNlYVh2L3NrNERITm5JMmZGVnRvWEcvMEJqQlVVdDBGVkpseEdORWdaR01DYmh0M0FnOVpXb2swRnI4WQprSW9GaUdKdlFrc21IR1FOV29VSjZUMDF5RVRxd2xZditySmwxd2lMWHB4bmgvSXg2dzJiS3lsOGQwb3lxZE13ClV4QkpBb0dBSDVMR3BwWlo5MlFqcURhVVoweXV1M043Rkd2bE1xMzBib2pNalFMRWFJcmpVZ0IwSnluVzIrY0gKT2RJTjhJaXZWSE9scEVlYktTa1BqU0ZqV2RNY3FZRElBNXRhbW4zWkcyWVJRQXpEUEpyZGVpR0M0Unl3NU1Regp1RnJBc2NQZTg4ZTh5MU1MUkNyTld3ZUtSR1VlZG1VUjgvZ2t6a0d4TnZGV3JXOHRoSFU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: linkerd2/templates/sp-validator-rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-linkerd-sp-validator
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: linkerd
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
# Source: linkerd2/templates/sp-validator-rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-linkerd-sp-validator
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: linkerd
subjects:
- kind: ServiceAccount
  name: linkerd-sp-validator
  namespace: linkerd
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: linkerd-linkerd-sp-validator
  apiGroup: rbac.authorization.k8s.io
---
# Source: linkerd2/templates/sp-validator-rbac.yaml
###
### Service Profile Validator RBAC
###
---
# Source: linkerd2/templates/sp-validator-rbac.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: linkerd-sp-validator-webhook-config
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: linkerd
webhooks:
- name: linkerd-sp-validator.linkerd.io
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
  clientConfig:
    service:
      name: linkerd-sp-validator
      namespace: linkerd
      path: "/"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lSQUlMcit5dG5RdUR3MzFNQnZMSHBSODh3RFFZSktvWklodmNOQVFFTEJRQXcKS3pFcE1DY0dBMVVFQXhNZ2JHbHVhMlZ5WkMxemNDMTJZV3hwWkdGMGIzSXViR2x1YTJWeVpDNXpkbU13SGhjTgpNakF3TnpJNU1UY3lNakF3V2hjTk1qRXdOekk1TVRjeU1qQXdXakFyTVNrd0p3WURWUVFERXlCc2FXNXJaWEprCkxYTndMWFpoYkdsa1lYUnZjaTVzYVc1clpYSmtMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU0zTVRnbmcxdVloQkh2R1FJVnpYNkdsOWt0MGhETXBHTkQyY0k3S0s1YzNnaDVHVDlzaApLQWJRTGd4bTc5d1VzbzJIWTRQNWIxcURROHo4dHF1V2VkK0xKWEVoeFd5Rk43MUdZVWRsVkhNdWRBNE0yRFNICnRUTkVlWDNDZEJQYlpZMnl2blhlT1hJL0VBK2d5b0IyWVVXaHRmS3ZZTzgways4ZDQ2TnR1RTh0ZDVjUm1zQnQKNDhURElneGl5Y3JPYnVVSndCbTRCTXlrN1N0NFhKRTZZTGRiT0c3aENZOXZBTTg5a3FOZmpZdGhmNXhiRFZMLwphNm00ZTRoOUNRTG0wT3VSMWdYc0gxZU42YVZkNG9OUmxaRW50Q3MyWWVWWitDQ1kzYUl3U3BadnJQUkRJNzBQCjUxSDN5VU1oRElKZnNCUkRNLzFSOHVNbytVYW50REMvblprQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUUQKQWdLa01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDc0VyOXYxeUhCblBuWGp2WXBZOW1tM2JORUFSMlZiRXdJClZ5dUZrRmlCemdnNm1vaE54TEphY0JCVCtYT09IQzBlOHltdzRndzRpckR6Z3lVbzZmZERXQ0RpaktsVllwNTAKQkl3c1N1bVZZSFZhcUNzcENJNnZYdzY3RVFzL2hMVHNOVWVqanc0Z0dKSy9CSGtJYk85WWdibFRQd1lyU2V6WApSU0hTKzJ6RUpTOUZMSVJ2akhDWXdrV2RWWk9BLzU4eDI2UmlJRXZpS0ZuTHd0YVJaR09HK0hoNUlpQTZ5OWRkCmozMjVZRnZ1dFMzN3RwakxpMXQwd0VNWUtIeHZ5MU5MWkpJbHRFYlY1dEcvajFrY0U4QU1KVk5DUjRjMHRTVjkKK3lueE5sR1BPK2ZNU0luczNpNlI5cTN6R2xzb1lDb0s2N3JWWFE0blFWdDF6QXZvS0ZDcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  failurePolicy: Fail
  rules:
  - operations: [ "CREATE" , "UPDATE" ]
    apiGroups: ["linkerd.io"]
    apiVersions: ["v1alpha1", "v1alpha2"]
    resources: ["serviceprofiles"]
  sideEffects: None
