---
# Source: argo-cd/templates/argocd-server/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-argocd-server
spec:
  rules:
    - host: delivery.staging.test.io
