apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            cpu: '1'
            memory: 2048Mi
          requests:
            cpu: '0.25'
            memory: 512Mi

