apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

nameSuffix: -dev

configMapGenerator:
  - name: users-dbs-config
    files:
      - config-files/authentication.sql

patchesStrategicMerge:
  - capacity-planning.yml