apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            cpu: '4'
            memory: 4096Mi
          requests:
            cpu: '2'
            memory: 1024Mi

