---
# Source: argo-cd/templates/redis/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-argocd-redis
  labels:
    app.kubernetes.io/name: argocd-redis
    helm.sh/chart: argo-cd-2.5.4
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: redis
    app.kubernetes.io/version: 5.0.8    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-redis
        helm.sh/chart: argo-cd-2.5.4
        app.kubernetes.io/instance: argo
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/component: redis
        app.kubernetes.io/version: 5.0.8
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: argo-argocd-redis
        args:
        - --save
        - ""
        - --appendonly
        - "no"
        image: redis:5.0.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          {}
