apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - role.yaml
  - role-binding.yaml
  - sealedsecret-crd.yaml
  - service.yaml
  - service-account.yaml

namespace: kube-system

commonLabels:
  app: sealed-secrets-controller

images:
  - name: sealed-secrets-controller
    newName: quay.io/bitnami/sealed-secrets-controller
    newTag: v0.12.4