---
# Source: sealed-secrets/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-controller-key-admin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.10.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.12.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-controller-key-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: sealed-secrets-controller
    namespace: kube-system
---
# Source: sealed-secrets/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-controller-service-proxier
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.10.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.12.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-controller-service-proxier
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
