apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - crds/
  - roles/
  - v0.15.0/

namespace: kube-system

images:
  - name: contour
    newName: gcr.io/heptio-images/contour
    newTag: v0.15.0
  - name: envoy
    newName: docker.io/envoyproxy/envoy
    newTag: v1.11.1
  - name: envoy-initconfig
    newName: gcr.io/heptio-images/contour
    newTag: v0.15.0

commonLabels:
  app.kubernetes.io/name: contour
  app.kubernetes.io/instance: contour
  app.kubernetes.io/managed-by: Helm