apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - service.yaml
  - dashboard-service.yaml
  - dashboard-ingress.yaml
  - default-cert-secret.yaml
  - hpa.yaml
  - deployment.yaml

namespace: kube-system

images:
  - name: traefik
    newName: traefik
    newTag: 1.7.21

commonLabels:
  app: traefik

commonAnnotations:
  contact: '+15148889999'

configMapGenerator:
  - name: traefik
    files:
      - config-files/traefik.toml