apiVersion: v1
data:
  authentication.sql: |-
    -- Databases.
    CREATE DATABASE IF NOT EXISTS test_db_prod;

    -- Users.
    CREATE USER IF NOT EXISTS 'test_user_prod'@'localhost' IDENTIFIED BY 'some_password';

    -- Alters.
    ALTER USER 'test_user_prod'@'localhost' IDENTIFIED BY 'some_password';

    -- Privileges.
    GRANT ALL PRIVILEGES ON test_db_prod.* TO 'test_user_prod' identified by 'some_password';

    -- Max Connexions.
    SET GLOBAL max_connections = 2048;
kind: ConfigMap
metadata:
  name: users-dbs-config-prod-862k9bd25k
---
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: c29tZV9oYXJkX3Bhc3N3ZA==
kind: Secret
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: root-db-credentials-prod-28c7784khc
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: mysql-prod
  namespace: default
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: mysql-prod
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        contact: "+15148889999"
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 15
          periodSeconds: 10
        name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          limits:
            cpu: "4"
            memory: 4096Mi
          requests:
            cpu: "2"
            memory: 1024Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: mysql-prod
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
