apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: c29tZV9oYXJkX3Bhc3N3ZA==
kind: Secret
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: root-db-credentials-ffmh4hd7b6
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        contact: "+15148889999"
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 15
          periodSeconds: 10
        name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.5"
            memory: 1024Mi
          requests:
            cpu: "0.125"
            memory: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    contact: "+15148889999"
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
