apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - image: mysql
        name: mysql
        envFrom:
          - secretRef:
              name: root-db-credentials
          - configMapRef:
              name: users-dbs-config
        livenessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - -h
              - localhost
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - -h
              - localhost
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          limits:
            cpu: '0.5'
            memory: 1024Mi
          requests:
            cpu: '0.125'
            memory: 512Mi
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-pvc
          - mountPath: /var/lib/mysql-root-credentials
            name: mysql-root-credentials
          - mountPath: /var/lib/mysql-users-dbs-config
            name: mysql-users-dbs-config
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql
        - name: mysql-root-credentials
          secret:
            secretName: root-db-credentials
        - name: mysql-users-dbs-config
          configMap:
            name: users-dbs-config

