apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - pvc.yml
  - service.yml
  - deployment.yml

namespace: default

images:
  - name: mysql
    newName: mysql
    newTag: 5.7.22

secretGenerator:
  - name: root-db-credentials
    envs:
      - ./config-files/db.env

commonLabels:
  app: mysql

commonAnnotations:
  contact: '+15148889999'