apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yml
  - service.yml
  - deployment.yml

namespace: default

images:
  - name: mysql
    newName: mysql
    newTag: 5.7.22

secretGenerator:
  - name: root-db-credentials
    env: ./config-files/db.env

configMapGenerator:
  - name: users-dbs-config
    files:
      - config-files/authentication.sql

commonLabels:
  app: mysql

commonAnnotations:
  contact: '+15148889999'